
1. Explain Docker Architecture.
A:  Docker architecture consists of three main components: 
      - Docker Client: The Docker Client is the primary interface for users to interact with Docker. It allows users to issue commands to manage containers, images, and other Docker resources.
      - Docker Daemon/Host: The Docker Daemon is responsible for managing Docker objects such as images, containers, networks, and volumes. It listens for Docker API requests and processes them accordingly.
      - Docker Registry: The Docker Registry is a storage and distribution system for Docker images. It  allows users to store and share Docker images. The most popular public registry is Docker Hub, but users can also set up private registries for their own use.
      On clould platforms , docker registrys are
      Aws : ECR (Elastic Container Registry)
      Azure : ACR (Azure Container Registry)
      GCP : GCR (Google Container Registry)



2. What is the difference between Virtual Machine and Docker Container?

A: The main difference between a Virtual Machine (VM) and a Docker Container is that a VM runs a full operating system on top of a hypervisor, while a Docker Container shares the host operating system's kernel and runs as an isolated process. VMs are heavier and require more resources, while Docker Containers are lightweight and more efficient. Additionally, VMs take longer to start up compared to Docker Containers, which can start in seconds.

- Virtual Machine:
  - Runs a full operating system
  - Requires a hypervisor
  - Heavier and resource-intensive
  - Longer startup time
- Docker Container:
  - Shares the host OS kernel
  - Runs as an isolated process
  - Lightweight and efficient

3. What are the Linux features that are necessary for a container?
A: The Linux features necessary for a container include:
    - Namespaces: Provide isolation for processes, network, and other resources.
    - Control Groups (cgroups): Limit and prioritize resource usage for containers.

4. What is the difference between Docker Image and Docker Container?
A:  - Docker Image: A Docker Image is a read-only template that contains the instructions for creating a Docker Container. It includes the application code, libraries, dependencies, and runtime environment. Images are used to create containers and can be shared and stored in registries.
   - Docker Container: A Docker Container is a runtime instance of a Docker Image. 


5. Can we delete an image when a container is stopped ?

A: Yes, you can delete a Docker image even if container is stopped . 
  you will be  able to delete the image forcefully .
 

6. How to install the latest version of Docker on Linux?

7. What is the difference between Docker and Docker Swarm?
A: 
    - Docker: Docker is a platform that allows you to develop, ship, and run applications in containers. It provides tools for building, managing, and deploying containerized applications on a single host.
    - Docker Swarm: Docker Swarm is a native clustering and orchestration tool for Docker. It allows you to manage a cluster of Docker hosts. With Docker Swarm, you can deploy and scale applications across multiple hosts, ensuring high availability and load balancing. It provides features like service discovery, rolling updates, and fault tolerance for containerized applications in a swarm cluster.


8. What are the different types of Docker Networks?
A: for Single Docker Host, there are three types of Docker Networks:
    - Bridge Network: The default network driver for containers on a single host. It allows containers to communicate with each other and the host. Docker0 is the default bridge network created by Docker.
    - Host Network: Containers share the host's network stack, allowing them to use the host's IP address and ports directly. It will not provide isolation between the container and the host, which can lead to security risks.
    - None Network: Containers have no network connectivity. They cannot communicate with other containers or the host.
      It will not provide any network isolation, and the container will not be able to access the network or communicate with other containers or the host, as there is no IP address assigned to the container.

   for Multi Docker Host, there are two types of Docker Networks:
      - Overlay Network: Allows containers running on different Docker hosts to communicate with each other. It uses VXLAN (Virtual Extensible LAN) to encapsulate network traffic between hosts.
      - Macvlan Network: Allows you to assign a MAC address to a container, making it appear as a physical device on the network. This allows containers to have direct access to the host's network and can be used for scenarios where you need to integrate with existing network infrastructure.

9. Give the command to create a Docker Container.
A: The command to create a Docker Container is:
   
     docker run --rm -d --name <container_name> -p <host_port>:<container_port> -v <docker_volume>:<container_path> -e <environment_variable>=<value> <image_name>

   
10. How do I list all containers in Docker including stopped containers and delete them?
A: 
    To list all containers in Docker, including stopped containers, you can use the following command:

        docker ps -a
    To delete all containers, including running containers without stopping them manually, you can use the following command:
        docker rm -f $(docker ps -aq)


11. Can I delete an image without stopping the container?

12. Can I delete all containers at once including running containers without stopping them manually?
A:     docker rm -f $(docker ps -aq)

13. How to check the logs of a container?
A: To check the logs of a container, you can use the following command:

    docker logs <container_name_or_id>
    docker logs -f --tail=100 <container_name_or_id>  # To follow the logs in real-time    

14. How do you go inside a container?
A: To go inside a container, you can use the following command:

    docker exec -it <container_name_or_id> /bin/bash
    # or
    docker exec -it <container_name_or_id> /bin/sh  

15. How to check the IP address of a container?
A: To check the IP address of a container, you can use the following command:

    docker inspect contname_or_cid | grep "IPAddress"
    

16. What is the lifecycle of a Docker Container?
A: The lifecycle of a Docker Container consists of the following stages:
    - : The container is created but not yet started.
    - Running: The container is actively running and executing its processes.
    - Paused: The container is temporarily paused, and its processes are suspended.
    - Stopped: The container has been stopped, and its processes have been terminated.
    - Deleted: The container has been removed from the system.

17. What is the difference between Docker Stop and Docker Pause?
A: 
    - Docker Stop: The `docker stop` command gracefully stops a running container by sending a SIGTERM signal to the main process inside the container. It allows the container to clean up resources and exit gracefully. If the container does not stop within a certain timeout period, it will be forcefully killed with a SIGKILL signal.
    - Docker Pause: The `docker pause` command temporarily suspends all processes in a running container. It effectively freezes the container's state, allowing you to resume it later without losing any data or state. When you unpause the container, all processes will continue from where they were paused.

18. How to delete all unused images, networks, stopped containers, and cache?
A: To delete all unused images, networks, stopped containers, and cache, you can use the following command:

    docker system prune -a

19. What are dangling images?
A: Dangling images are Docker images that are not tagged and are not referenced by any container. They are typically created during the build process when intermediate layers are generated but not used in the final image. These images can take up disk space and can be safely removed if they are no longer needed. 
You can identify dangling images using the following command:

    docker images -f "dangling=true"

20. Who is managing networking in Docker on Linux? How can you access a container without publishing the port?
A: On Linux, Docker uses the host's networking stack to manage container networking. By default, Docker creates a bridge network called "docker0" that allows containers to communicate with each other and the host. 
 
   To access a container without publishing the port, you can use the container's IP address assigned by Docker. You can find the container's IP address using the following command:

    docker inspect <container_name_or_id> | grep "IPAddress" 
   Then, you can access the container using its IP address and the appropriate port number for the service running inside the container.

21. How can I start multiple containers with a single command? What is Docker Compose?

    A: Docker Compose is a tool that allows you to define and manage multi-container Docker applications. It uses a YAML file to specify the services, networks, and volumes for your application. With Docker Compose, you can start multiple containers with a single command.
    To start multiple containers using Docker Compose, you can create a `docker-compose.yml` file with the necessary configuration for your services. Then, you can use the following command to start all the containers defined in the Compose file:

    docker-compose up -d

22. How do you persist/save data in a Docker container? .

A: To persist/save data in a Docker container, you can use Docker Volumes or Bind Mounts.
    - Docker Volumes: Docker Volumes are managed by Docker and provide a way to store data outside of the container's filesystem. You can create a volume using the following command:

        docker volume create <volume_name>
      Then, you can mount the volume to a container using the `-v` or `--mount` flag when running the container:

        docker run -v <volume_name>:<container_path> <image_name>

    - Bind Mounts: Bind Mounts allow you to mount a directory from the host machine into the container. You can use the `-v` or `--mount` flag to specify the host directory and the container path:
        docker run -v <host_directory>:<container_path> <image_name>

23. How to save a running container to a TAR file?
A: To save a running container to a TAR file, you can use the `docker export` command. This command exports the filesystem of the container as a TAR archive. Here is the syntax:

    docker export <container_name_or_id> -o <output_file.tar>

24. How to import a TAR file as a Docker image?
A: To import a TAR file as a Docker image, you can use the `docker import` command. This command creates a new Docker image from the contents of the TAR file. Here is the syntax:

    docker import <input_file.tar> <image_name>

25. How can you convert a running container into an image?
A: To convert a running container into an image, you can use the `docker commit` command. This command creates a new image from the current state of the container. Here is the syntax:

    docker commit <container_name_or_id> <new_image_name>

26. How to convert an existing image into a TAR file?
A: To convert an existing Docker image into a TAR file, you can use the `docker save` command. This command saves one or more images to a TAR archive. Here is the syntax:

    docker save <image_name> -o <output_file.tar>

27. How to load a TAR file as a Docker image?
A: To load a TAR file as a Docker image, you can use the `docker load` command. This command loads an image from a TAR archive. Here is the syntax:

    docker load -i <input_file.tar>
